### ISSUE TITLE
Bundle mat file missing

### ISSUE THREAD

**Issue by prechtl** [alcor-vision/confidence-fusion#1]
Hi,  Thanks for making the project available.   I'm trying to run your demo_kitti.m.  At one point it tries to load the file 'bundle_loc_viso_testing.mat'.  However, I was not able to locate that file in any of the downloaded content from Kitti or the kitti_2012_mv_cm-cnn.zip.  Can you provide a link to this .mat file so the demo script will run to completion?

**Comment by mdouskos** [comment]
Thank you for your interest in our work and for pointing out this bug. The pre-computed KITTI 2012 localization files are now available in the `data` folder.

**Comment by prechtl** [comment]
Thanks
