### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by zyfsa** [alcor-vision/confidence-fusion#2]
when I git the rep, so I "cd" the dir, cuda.
Then, I use "make"
I get this problem: make: *** No rule to make target 'diff.h', needed by 'tvq2opt'.  Stop.
please how to fix it ? thanks

**Comment by mdouskos** [comment]
The Makefile was outdated, thanks for pointing this out. 
I have pushed a commit with the correct Makefile.
Let me know if you still face any issues.
